### ISSUE TITLE
Research on basic bot detection model

### ISSUE THREAD

**Issue by kooreshakhbari** [Bot-FBI/Issue-Tracker#4]
Understand how our bot detection model will work. What inputs it requires, what its output will be etc...

**Comment by XiuLuoShen** [comment]
Data:

https://botometer.osome.iu.edu/bot-repository/datasets.html

**Comment by XiuLuoShen** [comment]
Simple model that predicts bot or not with 98% accuracy based on account info only. https://colab.research.google.com/drive/1mo0a_Pi5HaFr5xEh4T9RmOXuruzKvIpX?authuser=1#scrollTo=8KVZUbK8k3jH

**Comment by XiuLuoShen** [comment]
Next steps:
1. Working with tweets
2. Applying NLP models to tweets

**Comment by XiuLuoShen** [comment]
Got basic RNN model to work with tweets.

Next steps:
Apply NLP models to tweets
Combining account and tweet models - prototype such that we are comfortable doing it. Training would involve full account and tweet data as one data sample.

**Comment by XiuLuoShen** [comment]
Combined account and tweet models into a prototype.
